import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Header from "~/components/Header";
import CreateTask from "~/components/CreateTask";
import Tasks from "~/components/Tasks";
import { mock } from "~/utils/mock";
import { useUser } from "@clerk/nextjs";
import React from "react";
import { Task } from "@prisma/client";
import {
  useDescriptionCompletion,
  useSuggestionCompletion,
} from "~/utils/openai";

const Home: NextPage = () => {
  const [inputValue, setInputValue] = React.useState<string | undefined>(
    undefined
  );

  const utils = api.useContext();

  const { user } = useUser();

  const tasks = api.tasks.getAll.useQuery({ userId: user?.id || "" });

  const addTask = api.tasks.create.useMutation({
    async onSuccess() {
      await utils.tasks.getAll.invalidate();
    },
  });

  const addSuggestions = api.tasks.createSuggestions.useMutation({
    async onSuccess() {
      await utils.tasks.getAll.invalidate();
    },
  });

  const completeSuggestion = api.tasks.completeSuggestion.useMutation({
    async onSuccess() {
      await utils.tasks.getAll.invalidate();
    },
  });

  const handleCreateDescription = async (task: string) => {
    return await useDescriptionCompletion(task);
  };

  const handleCreateSuggestions = async (task: string) =>
    await useSuggestionCompletion(task);

  const handleCompleteSuggestion = async (id: string, completed: boolean) =>
    await completeSuggestion.mutateAsync({
      id,
      completed,
    });

  const handleSubmit = async () => {
    const description = await handleCreateDescription(inputValue!);

    const task = await addTask.mutateAsync({
      task: inputValue!,
      description: (description as any).text.trim().split("\n")[0],
      userId: user!.id,
    });

    const suggestionsCompletions = await handleCreateSuggestions(task.task);

    const suggestions = await addSuggestions.mutateAsync({
      tasks: suggestionsCompletions || [],
      taskId: task.id,
    });

    setInputValue("");
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen justify-center overflow-hidden bg-black">
        <div className="m-4 flex w-full flex-col rounded-md bg-white p-4">
          <Header />
          <Tasks
            tasks={tasks.data}
            onCompleteSuggestion={handleCompleteSuggestion}
          />
          <CreateTask
            value={inputValue}
            onChangeInput={(value) => setInputValue(value)}
            onSubmit={handleSubmit}
          />
        </div>
      </main>
    </>
  );
};

export default Home;
